### ISSUE TITLE
some question about data augmentation

### ISSUE THREAD

**Issue by Vipning** [liftkkkk/Bi_NER#1]
Hey，in your paper，when you sample the sentences ，does the Uniform(S) mean to select a sentence from the set S with equal probability?And，what the mean of  Binomial(E j \{a (i,k) })？Except for a(i,k), for each element in the set S that selected with a probability of 0.5?

**Comment by liftkkkk** [comment]
Yes, Uniform(S) mean to select a sentence from the set S with equal probability. Binomial(E j {a (i,k) }) means that each element (Except for a(i,k)) in S has the probability to be selected to augment the sentence. The process of selecting how many entities is a binomial process Binomial(p). We can conduct Bernoulli(p) experiment for each entity. You can set any probability p and then generate many new samples.

**Comment by liftkkkk** [comment]
> Hey，in your paper，when you sample the sentences ，does the Uniform(S) mean to select a sentence from the set S with equal probability?And，what the mean of Binomial(E j {a (i,k) })？Except for a(i,k), for each element in the set S that selected with a probability of 0.5?

Yes, Uniform(S) mean to select a sentence from the set S with equal probability. Binomial(E j {a (i,k) }) means that each element (Except for a(i,k)) in S has the probability to be selected to augment the sentence. The process of selecting how many entities is a binomial process Binomial(p). We can conduct Bernoulli(p) experiment for each entity. You can set any probability p and then generate many new samples.
